# Generated by Django 2.1.1 on 2018-09-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0002_auto_20180901_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='city',
        ),
    ]
