# Generated by Django 2.1 on 2018-09-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0003_auto_20180901_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='desc',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='location',
            name='icon',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='location',
            name='temp',
            field=models.FloatField(blank=True, default=25),
            preserve_default=False,
        ),
    ]
