# Generated by Django 2.1 on 2018-09-01 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0004_auto_20180901_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='desc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='icon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
