# Generated by Django 2.1 on 2018-09-01 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('weatherApp', '0005_auto_20180901_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.DateField(default=datetime.datetime(2018, 9, 1, 23, 15, 25, 511856, tzinfo=utc)),
        ),
    ]
